sudo: false
language: python
python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - nightly
env:
    - FRAMEWORK=django~=1.11.0
    - FRAMEWORK=django~=2.2.0
    - FRAMEWORK=django~=3.0.0
    - FRAMEWORK=django~=3.1.0
    - FRAMEWORK=flask~=1.0.0
    - FRAMEWORK=flask~=1.1.0
matrix:
    allow_failures:
        - python: nightly
    exclude:
        - python: 3.8
          env: FRAMEWORK=django~=1.11.0
        - python: 3.9
          env: FRAMEWORK=django~=1.11.0
        - python: nightly
          env: FRAMEWORK=django~=1.11.0
    fast_finish: true
branches:
    except:
        - mrosemartin84
        - soapbox
install:
    - pip install --quiet "${FRAMEWORK}"
    - pip install --quiet --requirement=tests/requirements.txt
    - pip install --quiet --editable .
script:
    - pytest --cov=soapfish
